version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: mlflow-postgres
    networks:
      - mlflow-net
    ports:
      - "5432:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    build:
      context: ../
      dockerfile: docker/Dockerfile.mlflow
    container_name: mlflow-server
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mlflow-net
    ports:
      - "${MLFLOW_PORT}:${MLFLOW_PORT}"
    env_file:
      - ../.env
    environment:
      - GUNICORN_CMD_ARGS=--timeout 60
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    command: >
      server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0
      --port ${MLFLOW_PORT}
      --serve-artifacts
      --allowed-hosts "*"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MLFLOW_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  podcast-classifier:
    build:
      context: ..
      dockerfile: docker/podcast.classifier
    container_name: podcast-classifier
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - mlflow-net
    env_file:
      - ../.env
    volumes:
      - ../data/annotated:/app/data/annotated
      # - ../models:/app/models

networks:
  mlflow-net:
    driver: bridge

volumes:
  postgres_data:
  mlflow_artifacts:
